export const data = [
  {
    id: 1,
    nom: "Apprendre les base",
    lien: "https://www.youtube.com/embed/cngh6fCaRi",
    categorie: "camera",
    auteur: "sikana",
        tags: ["camera", "sikana", "all"],
    img:" {}",
  },
  {
    id: 2,
    nom: "postes et rôles des joueurs",
    lien: "https://www.youtube.com/embed/dXMoxB0fvjA",
    categorie: "camera",
    auteur: "sikana",
    tags: ["camera", "sikana","all"],
  },
  {
    id: 3,
    nom: "règle du marcher",
    lien: "https://www.youtube.com/embed/G7x3MSjcRz0",
    categorie: "camera",
    auteur: "sikana",
    tags: ["camera", "sikana"],
  },
  {
    id: 4,
    nom: "fautes au basket",
    lien: "https://www.youtube.com/embed/PYpzcxrnd9I",
    categorie: "camera",
    auteur: "sikana",
    tags: ["camera", "sikana"],
  },
  {
    id: 5,
    nom: "les arrêts et les départs en dribble",
    lien: "https://www.youtube.com/embed/-g_zsC0yOC8",
    categorie: "Drible",
    auteur: "sikana",
    tags: ["Drible", "sikana"],
  },
  {
    id: 6,
    nom: "DRIBBLER COMME UN PRO",
    lien: "https://www.youtube.com/embed/JcoL8Wm79U0",
    categorie: "Drible",
    auteur: "Handle Your Game",
    tags: ["Drible", "Handle Your Game"],
  },
  {
    id: 7,
    nom: "DRIBBLE (Niveau 1)",
    lien: "https://www.youtube.com/embed/DV_Y3-NHh1w&t=1s",
    categorie: "Drible",
    auteur: "Handle Your Game",
    tags: ["Drible", "Handle Your Game"],
  },
  {
    id: 8,
    nom: "DRIBBLE (Niveau 2)",
    lien: "https://www.youtube.com/embed/MqUAOkUFnU0",
    categorie: "Drible",
    auteur: "Handle Your Game",
    tags: ["drible", "Handle Your Game"],
  },
  {
    id: 9,
    nom: " LES DIFFÉRENTS TIRS",
    lien: "https://www.youtube.com/embed/IiyzTQIFdPM",
    categorie: "Drible",
    auteur: "Handle Your Game",
    tags: ["Tires", "Handle Your Game"],
  },
  {
    id: 10,
    nom: "Apprendre à tirer",
    lien: "https://www.youtube.com/embed/QdFQjS6EToA",
    categorie: "Drible",
    auteur: "sikana",
    tags: ["Tires", "Sikana"],
  },
];
